### ISSUE TITLE
Lagrangian Regularization Question

### ISSUE THREAD

**Issue by RSirimanne** [pderian/PyTyphoon#3]
Salut Derian! 

Thanks so much for providing this code! I've been using it to get my head around a lot of concepts in your thesis and its helped a lot. 

I've used the connection coefficients function to compute the Laplacian regularization and have gotten nice results.

I had a question regarding the test of the regularization schemes that you have coded in the demo (L1 & Horn Schunk). My question is regarding the computation of the regularization term in physical space versus wavelet space and the comparison of their values with respect to the formula for the laplacian: 

![image](https://github.com/pderian/PyTyphoon/assets/60444590/c6c10dc7-280b-4390-976d-998509c48375)

Are you expecting exact agreement between these two terms for every level of the transform, or is some error acceptable? Additionally, do you expect this agreement to get much better for a wavelet basis with a much higher number of vanishing moments? 

Thanks in advance!

**Comment by pderian** [comment]
Hi @RSirimanne,
Well to be honest it's been a while since I worked on this, so please take everything I say with caution :)

- theoretically the level (depth) of the transform should have no impact. In practice I suspect it does, I would expect the error to increase with the depth... 

- generally you need enough vanishing moments (VM) so that the high-order terms are meaningful. But many VM also means longer filters, which may introduce numerical errors (and more computations). So, maybe "a bit more VM thant the bare minimum required for the chosen derivation order, but not much more than that" :)

I have a more complete version of the file, with more regularizers, convolution -based AND matrix-based regularizers, and more tests. In fact I had completely forgotten about it, your message lead me to rediscover it. It appears I never pushed it because there was a remaining bug, and I was likely overwhelmed by another topic and left things as they were. Standby a little bit, I'll try to fix it. If you don't see anything by the end of next week, remind me and I'll push it as it is.

**Comment by RSirimanne** [comment]
Ah yes! 

Both of those two points are consistent with my observations. As far as I've seen, the value of the regularization term is constant regardless of the depth of the transform as theory would suggest! And I'm noticing an ideal number of VM's between the highs and lows that give me the lowest error.

As a matter of fact I've just implement the matrix based regularization myself and gotten consistent result with my current convolutional form! So will be excited to see your tests in that regard!

**Comment by pderian** [comment]
Hi,

I made minor changes and pushed the file. You'll noticed a whole lot of new stuff.

A few remarks:

- don't pay too much attention to the high relative error on div and grad(div) regularizers, the reference motion field has null-divergence by construction and so any small absolute error results in a big relative error.
- for some reason **the matrix-based Laplacian regularizer has a significant worse error than the convolution-based one**. I haven't found the bug yet, if any...
- the convolution-based implementation has a norm() method which returns wrong results (by a constant factor) for even derivation orders (see the checkConv() test). There again I don't know where it comes from, and sadly I can't afford to spend too much time on it right now. 

Please, feel free to complete / correct / ... as you like!

**Comment by RSirimanne** [comment]
Thankyou so much! If I do find/correct the bug, I shall let you know! 

Aussi, merci meilleur pour m'aide! J'ai remarque que vous etuidez a l'universite de Rennes? C'est cool! Pendant Le Mars dernier, j'etais a Renne pour mes vacances. C'etait genial!
